version: '3.9'

services:
  db:
    restart: always
    image: postgres:14.7-alpine
    container_name: qortex_db
    env_file:
      - .env.docker
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U qortex_user" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8004:8000'
    volumes:
      - static_music:/code/staticfiles
      - .env.docker:/code/.env
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn qortexProject.wsgi:application -b :8000"

volumes:
  postgres_data:
  static_music:
